### ISSUE TITLE
CVE-2021-3411 accesses /proc/self/cmdline

### ISSUE THREAD

**Issue by vt-alt** [evdenis/cvehound#28]
The check for CVE-2021-3411 reads `/proc/self/cmdline`. Isn't the tool is designed to check _sources dump_ and not real time system?

**Comment by evdenis** [comment]
> Isn't the tool is designed to check sources dump and not real time system?

Exactly. This rule doesn't check real time system because it's not /proc/cmdline (kernel cmdline) it's /proc/self/cmdline (process own cmdline).

In this rule coccinelle is not enough to check CVE-2021-3411 because there is an assembly file arch/x86/kernel/vmlinux.lds.S and coccinelle can't match asm. However, in a coccinelle rule one can write a python code and check an asm file with an regexp https://github.com/evdenis/cvehound/blob/master/cvehound/cve/CVE-2021-3411.cocci#L19. Unfortunately, I can't get a list of spatch arguments (files to check) with sys.argv and the only way to get argv that I found is to read them from /proc/self/cmdline. So the only reason I read /proc/self/cmdline here is to get argv arguments of spatch (these arguments) and to find a full path to vmlinux.lds.S:

>spatch --no-includes --include-headers -D detect --no-show-diff -j 4 -I /home/work/workspace/linux/arch/x86/include -I /home/work/workspace/linux/arch/x86/include/generated -I /home/work/workspace/linux/arch/x86/include/uapi -I /home/work/workspace/linux/arch/x86/include/generated/uapi -I /home/work/workspace/linux/include -I /home/work/workspace/linux/include/uapi -I /home/work/workspace/linux/include/generated/uapi --include /home/work/workspace/linux/include/linux/kconfig.h --chunksize 1 --cocci-file /home/work/workspace/cvehound/cvehound/cve/CVE-2021-3411.cocci /home/work/workspace/linux/arch/x86/kernel/kprobes/opt.c /home/work/workspace/linux/arch/x86/kernel/vmlinux.lds.S

You can disable this rule with `--exclude CVE-2021-3411`

**Comment by vt-alt** [comment]
IC. Thanks for the answer!
